name: Build and Deploy Image

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build . -t kzdv/flight-parser:dev
      - name: Push Docker Image
        run: docker push kzdv/flight-parser:dev
      - name: Deploy image to cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECTL }}
        with:
          args: rollout restart deployment/flight-parser -n dev